### ISSUE TITLE
Co-Parents Not Appearing for Parent Profile

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-my-content#46]
When I try to add a co-parent to a parent profile, I receive the following screen: 
<img width="330" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-my-content/assets/74552270/115953b6-4093-4fa4-bea3-9ead70de0953">

Instead, a list of available parents should appear.

**Comment by esmeetewinkel** [comment]
This needs some dev work, outlined in PR https://github.com/IDEMSInternational/parenting-app-ui/pull/2127. What remains to do is resolving the bugs on this PR (which Johnny is working on right now) and then integrating the new functions in the spreadsheets (which I can start on as soon as this PR is merged)
